// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG3ZBhCFypVltwAeHa38glj7rH94aqK24',
    appId: '1:221870413468:android:f5323fc2c103cc82e4bf59',
    messagingSenderId: '221870413468',
    projectId: 'music-c223e',
    storageBucket: 'music-c223e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk0i-7ZfqnOJjUeAiN4_plG_SL6Wu8e2E',
    appId: '1:221870413468:ios:1c008d516e22bff3e4bf59',
    messagingSenderId: '221870413468',
    projectId: 'music-c223e',
    storageBucket: 'music-c223e.firebasestorage.app',
    androidClientId: '221870413468-gl6vb7iaq5o61p8mpu5ipfvtm3c3ptsk.apps.googleusercontent.com',
    iosClientId: '221870413468-s6ka9vu9el944elv1ib7i9om0921aboj.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicApp',
  );

}